apiVersion: v1
kind: ConfigMap
metadata:
  name: musk-xchat-web
data:
  NODE_ENV: production
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_WEB_URL: https://musk-xchat.lol
  NEXT_PUBLIC_PROJECT_NAME: musk-xchat
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-KYC07NR878
  NEXT_PUBLIC_CLARITY_PROJECT_ID: wbfrqsuxcb
  NEXT_PUBLIC_DEFAULT_THEME: dark
  NEXT_PUBLIC_AUTH_DISABLED: "true"
