apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: musk-xchat-lol-tls
spec:
  secretName: musk-xchat-lol-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - musk-xchat.lol
    - www.musk-xchat.lol
