apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloodhounds-preview
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bloodhounds.144.91.77.245.sslip.io
      secretName: bloodhounds-preview-tls
  rules:
    - host: bloodhounds.144.91.77.245.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bloodhounds-web
                port:
                  name: http
