FROM node:20-alpine AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    mkdir -p .next/build && \
    chown -R nextjs:nodejs /app

COPY --chown=nextjs:nodejs public ./public
COPY --chown=nextjs:nodejs .next/build/standalone ./
COPY --chown=nextjs:nodejs .next/build/static ./.next/build/static

USER nextjs

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

EXPOSE 3000

CMD ["node", "server.js"]
