apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musk-xchat
resources:
  - ../../base
images:
  - name: ghcr.io/example/musk-xchat
    newName: registry.144.91.77.245.sslip.io/musk-xchat
    newTag: "20260415125555"
